export { default as collegeRouter } from './college_router'
export { default as courseRouter } from './course_router'
export { default as universityRouter } from './university_router'
export { default as lectureRouter } from './lecture_router'
export { default as facultyRouter } from './faculty_router'
export { default as studentRouter } from './student_route'
export { default as superAdminRouter } from './super_admin_router'