export { default as collegeSchema } from './college_schema'
export { default as courseSchema } from './course_schema'
export { default as facultySchema } from './faculty_schema'
export { default as lectureSchema } from './lecture_schema'
export { default as studentSchema } from './student_schema'
export { default as superAdminSchema } from './super_admin_schema'
export { default as universitySchema } from './university_schema'
export { default as userSchema } from './user_schema'